language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe --white-list https://ipfs.io,slideshare,https://img.shields.io,https://codeclimate.com/github/unixorn/statsd-bash
